apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
